### ISSUE TITLE
CFAN not updating mods lately

### ISSUE THREAD

**Issue by Kabyl** [trakos/CFAN#9] opened 2016-07-11 22:08 UTC
**CFAN Version:**
0.1.0-0-g7256e64(beta)

**Operating System:** 
Windows 10 64bit

**The issue you are experiencing:** 
mods are not updating to latest version

**How to recreate this issue:** 
open or refresh cfan, the "add available updates" button has not lit up for a few days now, but when compared to https://mods.factorio.com/, there are newer versions than what i have installed.  For example, I have AutoTrash 0.1.1 installed via cfan, but on https://mods.factorio.com/, the author updated twice in the past 6 hours to 0.1.2 and now 0.1.3.  CFAN is not picking this up.  Either my CFAN isn't working properly, or I've done something wrong.

**CFAN error codes (if applicable):**
none

**Comment by trakos** [comment] 2016-07-12 08:21
You're right, there's some error on my server. I'm going to fix this in the evening. Sorry for any inconvenience caused by this.

**Comment by Kabyl** [comment] 2016-07-12 14:24
Hey! Thanks for looking into this for me. 

On a side note, I just want to say THANK YOU for your work on this.  I've used both CFAN and CKAN and these have saved me countless hours. :-)

**Comment by trakos** [comment] 2016-07-12 20:51
It should be fixed now.

Thanks for kind words!

**Closed as completed by trakos** 2016-07-12 20:51 UTC
